# Generated by Django 5.2.13 on 2026-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
