# Generated by Django 5.2.13 on 2026-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="female",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="internal_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
