# Generated by Django 5.2.13 on 2026-10-08 15:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_gender_userprofile_internal_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="female",
                max_length=6,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="internal_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Internal name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Telegram username"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
