# Generated by Django 5.2.13 on 2026-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="image",
            field=models.ImageField(blank=True, upload_to="options/"),
        ),
    ]
