# Generated by Django 5.2.13 on 2026-05-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_option_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="option",
            name="uniq_option_per_group",
        ),
    ]
