# Generated by Django 5.2.13 on 2026-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_option_uniq_option_per_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optiongroup",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
