# Generated by Django 5.2.13 on 2026-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_delivery_schedule_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="delivery_schedule_tier",
            field=models.CharField(
                choices=[
                    ("same_day", "Same day or later"),
                    ("next_day", "Next day or later"),
                    ("plus_2", "Two days or later"),
                    ("plus_3", "Three days or later"),
                ],
                default="same_day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_schedule_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same_day", "Same day or later"),
                    ("next_day", "Next day or later"),
                    ("plus_2", "Two days or later"),
                    ("plus_3", "Three days or later"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
