# Generated by Django 5.2.13 on 2026-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_category_delivery_schedule_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ka",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="name_ka",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="name_ru",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="name_ka",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="name_ru",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ka",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ka",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_ka",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
