# Generated by Django 5.2.13 on 2026-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_delivery_schedule_all_day_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiongroup",
            name="max_selections",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="min_selections",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
