# Generated by Django 5.2.13 on 2026-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_optiongroup_min_max_selections"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="category",
            name="page_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_description_ka",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_heading",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="category",
            name="page_heading_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_heading_ka",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_heading_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_slug",
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="category",
            name="page_slug_en",
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_slug_ka",
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_slug_ru",
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description_ka",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title_ka",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
