# Generated by Django 5.2.13 on 2026-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_category_seo_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page_slug_en", ""), _negated=True),
                fields=("page_slug_en",),
                name="uniq_category_page_slug_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page_slug_ka", ""), _negated=True),
                fields=("page_slug_ka",),
                name="uniq_category_page_slug_ka",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page_slug_ru", ""), _negated=True),
                fields=("page_slug_ru",),
                name="uniq_category_page_slug_ru",
            ),
        ),
    ]
