# Generated by Django 5.2.13 on 2026-08-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_category_page_slug_uniques"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("page_slug", models.SlugField(blank=True, max_length=140)),
                (
                    "page_slug_en",
                    models.SlugField(blank=True, max_length=140, null=True),
                ),
                (
                    "page_slug_ka",
                    models.SlugField(blank=True, max_length=140, null=True),
                ),
                (
                    "page_slug_ru",
                    models.SlugField(blank=True, max_length=140, null=True),
                ),
                ("page_heading", models.CharField(blank=True, max_length=200)),
                (
                    "page_heading_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "page_heading_ka",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "page_heading_ru",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("page_description", models.TextField(blank=True)),
                ("page_description_en", models.TextField(blank=True, null=True)),
                ("page_description_ka", models.TextField(blank=True, null=True)),
                ("page_description_ru", models.TextField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                (
                    "seo_title_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "seo_title_ka",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "seo_title_ru",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("seo_description", models.TextField(blank=True)),
                ("seo_description_en", models.TextField(blank=True, null=True)),
                ("seo_description_ka", models.TextField(blank=True, null=True)),
                ("seo_description_ru", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="category_landings/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landings",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("page_slug_en", ""), _negated=True),
                        fields=("page_slug_en",),
                        name="uniq_category_landing_page_slug_en",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("page_slug_ka", ""), _negated=True),
                        fields=("page_slug_ka",),
                        name="uniq_category_landing_page_slug_ka",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("page_slug_ru", ""), _negated=True),
                        fields=("page_slug_ru",),
                        name="uniq_category_landing_page_slug_ru",
                    ),
                ],
            },
        ),
    ]
