# Generated by Django 5.2.13 on 2026-10-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_seed_cakes_to_order_landing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["position", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="categorylanding",
            options={
                "ordering": ["slug"],
                "verbose_name": "Category landing",
                "verbose_name_plural": "Category landings",
            },
        ),
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["position", "name"],
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
            },
        ),
        migrations.AlterModelOptions(
            name="optiongroup",
            options={
                "ordering": ["name"],
                "verbose_name": "Option group",
                "verbose_name_plural": "Option groups",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["position", "-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptiongroup",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Product option group",
                "verbose_name_plural": "Product option groups",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="delivery_schedule_tier",
            field=models.CharField(
                choices=[
                    ("all_day", "All day"),
                    ("same_day", "Same day or later"),
                    ("next_day", "Next day or later"),
                    ("plus_2", "Two days or later"),
                    ("plus_3", "Three days or later"),
                ],
                default="same_day",
                max_length=20,
                verbose_name="Delivery schedule tier",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="categories/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ka",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_description",
            field=models.TextField(blank=True, verbose_name="Page description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_description_ka",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_heading",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_heading_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_heading_ka",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_heading_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_slug",
            field=models.SlugField(
                blank=True, max_length=140, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_slug_en",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_slug_ka",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_slug_ru",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description_ka",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title_ka",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="category_landings/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_description",
            field=models.TextField(blank=True, verbose_name="Page description"),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_description_ka",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Page description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_heading",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_heading_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_heading_ka",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_heading_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Page heading"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_slug",
            field=models.SlugField(
                blank=True, max_length=140, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_slug_en",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_slug_ka",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="page_slug_ru",
            field=models.SlugField(
                blank=True, max_length=140, null=True, verbose_name="Page slug"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO description"),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_description_ka",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO description"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_title_ka",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="seo_title_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SEO title"
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landings",
                to="catalog.category",
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="categorylanding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="option",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="catalog.optiongroup",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="options/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name_ka",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name_ru",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="option",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="option",
            name="price_delta",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Price delta"
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="is_required_default",
            field=models.BooleanField(default=True, verbose_name="Required by default"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="max_selections",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Maximum selections"
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="min_selections",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Minimum selections"
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name_ka",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name_ru",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="selection_type",
            field=models.CharField(
                choices=[("single", "Single"), ("multi", "Multi")],
                default="single",
                max_length=10,
                verbose_name="Selection type",
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Base price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_schedule_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all_day", "All day"),
                    ("same_day", "Same day or later"),
                    ("next_day", "Next day or later"),
                    ("plus_2", "Two days or later"),
                    ("plus_3", "Three days or later"),
                ],
                max_length=20,
                null=True,
                verbose_name="Delivery schedule tier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ka",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ka",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="option_groups",
            field=models.ManyToManyField(
                related_name="products",
                through="catalog.ProductOptionGroup",
                to="catalog.optiongroup",
                verbose_name="Option groups",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, max_length=200, verbose_name="Alt text"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Alt text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_ka",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Alt text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_ru",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Alt text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productoptiongroup",
            name="is_required",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is required"
            ),
        ),
        migrations.AlterField(
            model_name="productoptiongroup",
            name="option_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_links",
                to="catalog.optiongroup",
                verbose_name="Option group",
            ),
        ),
        migrations.AlterField(
            model_name="productoptiongroup",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="productoptiongroup",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_option_groups",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
    ]
