# Generated by Django 5.2.13 on 2026-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_deliverytimeslot_order_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank transfer"),
                ],
                max_length=15,
            ),
        ),
    ]
