# Generated by Django 5.2.13 on 2026-05-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_bank_transfer_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_instagram",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_telegram",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
