# Generated by Django 5.2.13 on 2026-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_customer_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="locale",
            field=models.CharField(default="en", max_length=5),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="address_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="address_ka",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="address_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="name_ka",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
