# Generated by Django 5.2.13 on 2026-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_backfill_pickuplocation_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
