# Generated by Django 5.2.13 on 2026-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
    ]
