# Generated by Django 5.2.13 on 2026-06-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_delivery_fee'),
        ('orders', '0008_order_delivery_fee_db_default'),
    ]

    operations = [
    ]
