# Generated by Django 5.2.13 on 2026-07-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_libertypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="environment",
            field=models.CharField(
                choices=[("prod", "Production"), ("dev", "Development")],
                default="prod",
                max_length=10,
            ),
        ),
    ]
