# Generated by Django 5.2.13 on 2026-10-08 15:11

import django.db.models.deletion
import orders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0017_alter_category_options_alter_categorylanding_options_and_more",
        ),
        ("orders", "0012_order_customer_email_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={
                "verbose_name": "Delivery address",
                "verbose_name_plural": "Delivery addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="libertypayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Liberty payment",
                "verbose_name_plural": "Liberty payments",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitemoption",
            options={
                "ordering": ["id"],
                "verbose_name": "Order item option",
                "verbose_name_plural": "Order item options",
            },
        ),
        migrations.AlterModelOptions(
            name="pickuplocation",
            options={
                "ordering": ["name"],
                "verbose_name": "Pickup location",
                "verbose_name_plural": "Pickup locations",
            },
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ["code"],
                "verbose_name": "Promo code",
                "verbose_name_plural": "Promo codes",
            },
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="apartment",
            field=models.CharField(blank=True, max_length=50, verbose_name="Apartment"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="building",
            field=models.CharField(blank=True, max_length=50, verbose_name="Building"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="city",
            field=models.CharField(max_length=120, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_address",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal code"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="street",
            field=models.CharField(max_length=200, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="amount_tetri",
            field=models.PositiveIntegerField(verbose_name="Amount in tetri"),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="currency",
            field=models.CharField(
                default="GEL", max_length=3, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liberty_payments",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="ordercode",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Order code"
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="pay_method",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Pay method"
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="raw_callback",
            field=models.TextField(blank=True, verbose_name="Raw callback"),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="testmode",
            field=models.BooleanField(default=False, verbose_name="Test mode"),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="transaction_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Transaction code"
            ),
        ),
        migrations.AlterField(
            model_name="libertypayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(max_length=254, verbose_name="Customer email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Customer Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=200, verbose_name="Customer name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(max_length=50, verbose_name="Customer phone"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_telegram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Customer Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                db_default=0,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Delivery fee",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Discount total",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="environment",
            field=models.CharField(
                choices=[("prod", "Production"), ("dev", "Development")],
                default="prod",
                max_length=10,
                verbose_name="Environment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                max_length=10,
                verbose_name="Fulfillment type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="locale",
            field=models.CharField(default="en", max_length=5, verbose_name="Locale"),
        ),
        migrations.AlterField(
            model_name="order",
            name="lookup_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Lookup token",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(
                default=orders.models._generate_order_number,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Number",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank transfer"),
                ],
                max_length=15,
                verbose_name="Payment method",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=10,
                verbose_name="Payment status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.pickuplocation",
                verbose_name="Pickup location",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.promocode",
                verbose_name="Promo code",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="timeslot_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Timeslot end"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="timeslot_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Timeslot start"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Line total"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=200, verbose_name="Product name"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Unit price"
            ),
        ),
        migrations.AlterField(
            model_name="orderitemoption",
            name="group_name",
            field=models.CharField(max_length=120, verbose_name="Group name"),
        ),
        migrations.AlterField(
            model_name="orderitemoption",
            name="option_name",
            field=models.CharField(max_length=120, verbose_name="Option name"),
        ),
        migrations.AlterField(
            model_name="orderitemoption",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="orders.orderitem",
                verbose_name="Order item",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemoption",
            name="price_delta",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Price delta"
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="address",
            field=models.CharField(max_length=300, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="address_en",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="address_ka",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="address_ru",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="name_ka",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Percent"), ("fixed", "Fixed")],
                default="percent",
                max_length=10,
                verbose_name="Discount type",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Discount value"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Max uses"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Minimum order amount",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="uses_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Uses count"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Valid from"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Valid to"),
        ),
    ]
