# Generated by Django 5.2.13 on 2026-10-08 15:11

import cart.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        (
            "catalog",
            "0017_alter_category_options_alter_categorylanding_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["added_at", "id"],
                "verbose_name": "Cart item",
                "verbose_name_plural": "Cart items",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitemoption",
            options={
                "verbose_name": "Cart item option",
                "verbose_name_plural": "Cart item options",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(
                default=cart.models._default_expires_at, verbose_name="Expires at"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="is_ordered",
            field=models.BooleanField(default=False, verbose_name="Is ordered"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Added at"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="cartitemoption",
            name="cart_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="cart.cartitem",
                verbose_name="Cart item",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.option",
                verbose_name="Option",
            ),
        ),
    ]
