# Generated by Django 5.2.13 on 2026-08-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrmOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("contact", models.TextField()),
                (
                    "fulfillment_type",
                    models.CharField(
                        choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                        default="delivery",
                        max_length=10,
                    ),
                ),
                ("weight", models.CharField(max_length=50)),
                ("filling", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("cake_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prepayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("terminal", "Terminal"),
                            ("tbc", "TBC Transfer"),
                            ("bog", "BOG Transfer"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "time_start"],
            },
        ),
        migrations.CreateModel(
            name="CrmOrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="crm_orders/")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="crm.crmorder",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
