# Generated by Django 5.2.13 on 2026-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_crmorder_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmorder",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
    ]
