# Generated by Django 5.2.13 on 2026-08-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_crmorder_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolvedYandexAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(unique=True)),
                ("yandex_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
