# Generated by Django 5.2.13 on 2026-08-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_crmorder_payment_type_crypto"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppNumberCheck",
            fields=[],
            options={
                "verbose_name": "WhatsApp number check",
                "verbose_name_plural": "WhatsApp number check",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crm.crmorder",),
        ),
    ]
