# Generated by Django 5.2.13 on 2026-08-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_whatsappnumbercheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppGetNewQr",
            fields=[],
            options={
                "verbose_name": "WhatsApp get new QR",
                "verbose_name_plural": "WhatsApp get new QR",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crm.crmorder",),
        ),
    ]
