# Generated by Django 5.2.13 on 2026-08-28 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_crmorder_taken_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crmorder",
            options={
                "ordering": [
                    "date",
                    models.Case(
                        models.When(
                            then=models.Value(1), time_start=datetime.time(0, 0)
                        ),
                        default=models.Value(0),
                        output_field=models.IntegerField(),
                    ),
                    "time_start",
                ]
            },
        ),
    ]
