# Generated by Django 5.2.13 on 2026-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_crmorder_website_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAddressResolveFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(unique=True)),
                ("failure_count", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ResolvedGoogleAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(unique=True)),
                ("google_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
