# Generated by Django 5.2.13 on 2026-09-04 08:32

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_crmorder_client_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmorder",
            name="client_token",
            field=models.CharField(
                db_index=True,
                default=crm.models.generate_crm_client_token,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
