# Generated by Django 5.2.13 on 2026-09-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0038_crmorder_flowwow_synced_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crmorder",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_orders_delivered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
