# Generated by Django 5.2.13 on 2026-09-23 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from crm.history import backfill_existing_crm_order_events


def backfill_crm_order_events(apps, schema_editor):
    backfill_existing_crm_order_events(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0039_crmorder_delivered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("crm", "CRM"),
                            ("admin", "Admin"),
                            ("website", "Website"),
                            ("flowwow", "Flowwow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crm.crmorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"], name="crm_order_event_order_at"
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_crm_order_events, migrations.RunPython.noop),
    ]
