# Generated by Django 5.2.13 on 2026-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0041_telegramnumbercheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolvedTelegramPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=15, unique=True)),
                ("resolved", models.BooleanField()),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, default="", max_length=32)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resolved Telegram phone",
                "verbose_name_plural": "Resolved Telegram phones",
            },
        ),
    ]
