# Generated by Django 5.2.13 on 2026-10-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0042_resolvedtelegramphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmorder",
            name="delivery_distance_meters",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmorder",
            name="delivery_duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmorder",
            name="delivery_route_computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeliveryRouteResolveFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failure_count", models.PositiveSmallIntegerField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.crmorder"
                    ),
                ),
            ],
        ),
    ]
