# Generated by Django 5.2.13 on 2026-10-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0043_crmorder_delivery_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("cash", "Cash"),
                            ("crypto", "Crypto"),
                            ("virtual", "Virtual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("currency", models.CharField(default="GEL", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                            ("withdrawal", "Withdrawal"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transfer_id", models.UUIDField(blank=True, null=True)),
                ("counterparty_name", models.CharField(blank=True, max_length=255)),
                ("counterparty_iban", models.CharField(blank=True, max_length=34)),
                ("description", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="crm.financialaccount",
                    ),
                ),
                (
                    "crm_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="crm.crmorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["date"], name="crm_fin_tx_date"),
                    models.Index(fields=["transfer_id"], name="crm_fin_tx_transfer"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("account", "external_id"),
                        name="uniq_fin_tx_account_external_id",
                    )
                ],
            },
        ),
    ]
