# Generated by Django 5.2.13 on 2026-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0044_financialaccount_financialtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="expense_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary"),
                    ("rent", "Rent"),
                    ("products", "Products"),
                    ("consumables", "Consumables"),
                    ("equipment", "Equipment"),
                ],
                max_length=20,
            ),
        ),
    ]
