# Generated by Django 5.2.13 on 2026-10-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0045_financialtransaction_expense_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("withdrawal", "Withdrawal"),
                    ("investment", "Investment"),
                    ("correction", "Correction"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
