# Generated by Django 5.2.13 on 2026-10-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0046_alter_financialtransaction_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="income_type",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("terminal", "Terminal")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="external_id",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
