# Generated by Django 5.2.13 on 2026-10-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0047_financialtransaction_income_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransaction",
            name="income_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("terminal", "Terminal"),
                    ("cash", "Cash"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
