# Generated by Django 5.2.13 on 2026-10-08 15:11

import crm.models
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0053_flowwow_withdrawals_to_transfers"),
        ("orders", "0013_alter_deliveryaddress_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crmorder",
            options={
                "ordering": [
                    "date",
                    models.Case(
                        models.When(
                            then=models.Value(1), time_start=datetime.time(0, 0)
                        ),
                        default=models.Value(0),
                        output_field=models.IntegerField(),
                    ),
                    "time_start",
                ],
                "verbose_name": "CRM order",
                "verbose_name_plural": "CRM orders",
            },
        ),
        migrations.AlterModelOptions(
            name="crmorderimage",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "CRM order image",
                "verbose_name_plural": "CRM order images",
            },
        ),
        migrations.AlterModelOptions(
            name="financialaccount",
            options={
                "verbose_name": "Financial account",
                "verbose_name_plural": "Financial accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="financialtransaction",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "Financial transaction",
                "verbose_name_plural": "Financial transactions",
            },
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="cake_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cake price"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="client_token",
            field=models.CharField(
                db_index=True,
                default=crm.models.generate_crm_client_token,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Client token",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="contact",
            field=models.TextField(verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_orders_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_orders_delivered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Delivered by",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="delivery_address",
            field=models.TextField(blank=True, verbose_name="Delivery address"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="delivery_distance_meters",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Delivery distance meters"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="delivery_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Delivery duration seconds"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="delivery_route_computed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivery route computed at"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="filling",
            field=models.CharField(max_length=255, verbose_name="Filling"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="flowwow_order_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Flowwow order id"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="flowwow_synced_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Flowwow synced description"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="flowwow_synced_internal_description",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Flowwow synced internal description",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="fulfillment_type",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                default="delivery",
                max_length=10,
                verbose_name="Fulfillment type",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="internal_description",
            field=models.TextField(blank=True, verbose_name="Internal description"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is paid"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nickname"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Payment date"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("cash", "Cash"),
                    ("terminal", "Terminal"),
                    ("tbc", "TBC Transfer"),
                    ("bog", "BOG Transfer"),
                    ("tbank", "T-Bank Transfer"),
                    ("flowwow", "Flowwow"),
                    ("crypto", "Cryptocurrency"),
                    ("online", "Online on website"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Payment type",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="phones",
            field=models.JSONField(default=list, verbose_name="Phones"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="prepayment",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prepayment"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("unconfirmed", "Unconfirmed"),
                    ("new", "New"),
                    ("in_work", "In work"),
                    ("ready", "Ready"),
                    ("client_approved", "Client approved"),
                    ("in_delivery", "In delivery"),
                    ("delivered", "Delivered"),
                ],
                default="new",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_orders_taken",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Taken by",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_media_ids",
            field=models.JSONField(default=list, verbose_name="Telegram media ids"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram message id"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_payload_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Telegram payload hash",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_posted_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Telegram posted date"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_posted_delivery_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Telegram posted delivery address"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_posted_time_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Telegram posted time end"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_posted_time_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Telegram posted time start"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="telegram_posted_when_ready",
            field=models.BooleanField(
                default=False, verbose_name="Telegram posted when ready"
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="time_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Time end"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="time_start",
            field=models.TimeField(blank=True, null=True, verbose_name="Time start"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="website_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_order",
                to="orders.order",
                verbose_name="Website order",
            ),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="weight",
            field=models.CharField(max_length=50, verbose_name="Weight"),
        ),
        migrations.AlterField(
            model_name="crmorder",
            name="when_ready",
            field=models.BooleanField(default=False, verbose_name="When ready"),
        ),
        migrations.AlterField(
            model_name="crmorderimage",
            name="image",
            field=models.ImageField(upload_to="crm_orders/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="crmorderimage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="crm.crmorder",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="crmorderimage",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="crmorderimage",
            name="source_url",
            field=models.TextField(blank=True, null=True, verbose_name="Source URL"),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="monthly_rent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Monthly rent",
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bank name"
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="currency",
            field=models.CharField(
                default="GEL", max_length=3, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="kind",
            field=models.CharField(
                choices=[
                    ("bank", "Bank"),
                    ("cash", "Cash"),
                    ("crypto", "Crypto"),
                    ("virtual", "Virtual"),
                ],
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="crm.financialaccount",
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="counterparty_iban",
            field=models.CharField(
                blank=True, max_length=34, verbose_name="Counterparty IBAN"
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="counterparty_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Counterparty name"
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="crm_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="financial_transactions",
                to="crm.crmorder",
                verbose_name="CRM orders",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="expense_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary"),
                    ("rent", "Rent"),
                    ("products", "Products"),
                    ("consumables", "Consumables"),
                    ("equipment", "Equipment"),
                ],
                max_length=20,
                verbose_name="Expense type",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="External id"
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="income_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("terminal", "Terminal"),
                    ("cash", "Cash"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
                verbose_name="Income type",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("withdrawal", "Withdrawal"),
                    ("investment", "Investment"),
                    ("correction", "Correction"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="matched_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crm.financialtransaction",
                verbose_name="Matched transaction",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="transfer_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Transfer id"),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="resolvedtelegramphone",
            name="checked_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Checked at"),
        ),
        migrations.AlterField(
            model_name="resolvedtelegramphone",
            name="number",
            field=models.CharField(max_length=15, unique=True, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="resolvedtelegramphone",
            name="resolved",
            field=models.BooleanField(verbose_name="Resolved"),
        ),
        migrations.AlterField(
            model_name="resolvedtelegramphone",
            name="user_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="User ID"),
        ),
        migrations.AlterField(
            model_name="resolvedtelegramphone",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="Username"
            ),
        ),
    ]
