# Generated by Django 5.2.13 on 2026-10-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0054_alter_crmorder_options_alter_crmorderimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTransactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("rent", "Rent"),
                            ("products", "Products"),
                            ("consumables", "Consumables"),
                            ("equipment", "Equipment"),
                            ("fees", "Fees"),
                        ],
                        max_length=20,
                        verbose_name="Expense type",
                    ),
                ),
                ("priority", models.IntegerField(verbose_name="Priority")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "operator",
                    models.CharField(
                        choices=[("and", "And"), ("or", "Or")],
                        max_length=3,
                        verbose_name="Operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial transaction rule",
                "verbose_name_plural": "Financial transaction rules",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="expense_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary"),
                    ("rent", "Rent"),
                    ("products", "Products"),
                    ("consumables", "Consumables"),
                    ("equipment", "Equipment"),
                    ("fees", "Fees"),
                ],
                max_length=20,
                verbose_name="Expense type",
            ),
        ),
        migrations.CreateModel(
            name="FinancialTransactionRuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("account_iban", "Account IBAN"),
                            ("counterparty_iban", "Counterparty IBAN"),
                            ("counterparty_name", "Counterparty name"),
                            ("description", "Description"),
                        ],
                        max_length=32,
                        verbose_name="Field",
                    ),
                ),
                ("pattern", models.CharField(max_length=512, verbose_name="Pattern")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="crm.financialtransactionrule",
                        verbose_name="Rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial transaction rule condition",
                "verbose_name_plural": "Financial transaction rule conditions",
                "ordering": ["id"],
            },
        ),
    ]
