# Generated by Django 5.2.13 on 2026-06-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendanceevent_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryCalculation",
            fields=[],
            options={
                "verbose_name": "Salary calculation",
                "verbose_name_plural": "Salary calculation",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("attendance.attendanceevent",),
        ),
    ]
