# Generated by Django 5.2.13 on 2026-10-08 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_salarycalculation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendanceevent",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Attendance event",
                "verbose_name_plural": "Attendance events",
            },
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="event_type",
            field=models.CharField(
                choices=[("arrival", "Arrival"), ("departure", "Departure")],
                max_length=10,
                verbose_name="Event type",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
